stages:
  - first
  - second
  - third

.build_template: &build_definition
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.18.0
    entrypoint: [""]
  before_script:
    - mkdir -p $DOCKER_CONFIG
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"clbbot\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > $DOCKER_CONFIG/config.json
    - export DOCKER_IMAGE_TAG_PATCH=`echo -n $DOCKER_IMAGE_TAG_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1.\2.\3/p'`
    - export DOCKER_IMAGE_TAG_MINOR=`echo -n $DOCKER_IMAGE_TAG_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1.\2/p'`
    - export DOCKER_IMAGE_TAG_MAJOR=`echo -n $DOCKER_IMAGE_TAG_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1/p'`
  script: 
    - | 
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --dockerfile $DOCKER_FILE_PATH/Dockerfile \
      --destination $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_PREFIX$DOCKER_IMAGE_TAG_REVISION \
      --destination $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_PREFIX$DOCKER_IMAGE_TAG_PATCH \
      --destination $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_PREFIX$DOCKER_IMAGE_TAG_MINOR \
      --destination $DOCKER_IMAGE:$DOCKER_IMAGE_TAG_PREFIX$DOCKER_IMAGE_TAG_MAJOR \
      --single-snapshot
  only:
    - tags

build-server:
  <<: *build_definition
  stage: first
  variables:
    DOCKER_CONFIG: /root
    DOCKER_IMAGE: cookielab/nodejs
    DOCKER_IMAGE_TAG_PREFIX: server-
    DOCKER_IMAGE_TAG_REVISION: $CI_COMMIT_TAG
    DOCKER_FILE_PATH: $CI_PROJECT_DIR/server

build-build:
  <<: *build_definition
  stage: second
  variables:
    DOCKER_CONFIG: /root
    DOCKER_IMAGE: cookielab/nodejs
    DOCKER_IMAGE_TAG_PREFIX: build-
    DOCKER_IMAGE_TAG_REVISION: $CI_COMMIT_TAG
    DOCKER_FILE_PATH: $CI_PROJECT_DIR/build

build-master:
  <<: *build_definition
  stage: third
  variables:
    DOCKER_CONFIG: /root
    DOCKER_IMAGE: cookielab/nodejs
    DOCKER_IMAGE_TAG_PREFIX: ''
    DOCKER_IMAGE_TAG_REVISION: $CI_COMMIT_TAG
    DOCKER_FILE_PATH: $CI_PROJECT_DIR
