stages:
  - first
  - second

build-server:
  stage: first
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_IMAGE: cookielab/nodejs
    DOCKER_IMAGE_VERSION_REVISION: $CI_COMMIT_TAG
  before_script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"clbbot\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > /root/.docker/config.json
  script:
    - export DOCKER_IMAGE_VERSION_PATCH=`echo -n $DOCKER_IMAGE_VERSION_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1.\2.\3/p'`
    - export DOCKER_IMAGE_VERSION_MINOR=`echo -n $DOCKER_IMAGE_VERSION_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1.\2/p'`
    - export DOCKER_IMAGE_VERSION_MAJOR=`echo -n $DOCKER_IMAGE_VERSION_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1/p'`
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/server/Dockerfile --destination $DOCKER_IMAGE:server-$DOCKER_IMAGE_VERSION_REVISION --destination $DOCKER_IMAGE:server-$DOCKER_IMAGE_VERSION_PATCH --destination $DOCKER_IMAGE:server-$DOCKER_IMAGE_VERSION_MINOR --destination $DOCKER_IMAGE:server-$DOCKER_IMAGE_VERSION_MAJOR
  tags:
    - docker
  only:
    - tags

build:
  stage: second
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_IMAGE: cookielab/nodejs
    DOCKER_IMAGE_VERSION_REVISION: $CI_COMMIT_TAG
  before_script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"clbbot\",\"password\":\"$DOCKER_HUB_PASSWORD\"}}}" > /root/.docker/config.json
  script:
    - export DOCKER_IMAGE_VERSION_PATCH=`echo -n $DOCKER_IMAGE_VERSION_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1.\2.\3/p'`
    - export DOCKER_IMAGE_VERSION_MINOR=`echo -n $DOCKER_IMAGE_VERSION_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1.\2/p'`
    - export DOCKER_IMAGE_VERSION_MAJOR=`echo -n $DOCKER_IMAGE_VERSION_REVISION | sed -n -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?/\1/p'`
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION_REVISION --destination $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION_PATCH --destination $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION_MINOR --destination $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION_MAJOR
  tags:
    - docker
  only:
    - tags
